
CREATE TABLE IF NOT EXISTS STUDENTS (
    STUDENT_ID TEXT,
    STUDENT_NAME TEXT,
    AGE INTEGER,
    STUDENT_SCORE REAL
);

INSERT INTO STUDENTS(STUDENT_ID, STUDENT_NAME, AGE, STUDENT_SCORE) VALUES
    ('10120', 'Jake', 15, 87),
    ('10215', 'Steve', 17, 91),
    ('10345', 'Bob', 14, 95),
    ('10413', 'Harry', 16, 99);

SELECT COUNT(STUDENT_ID) AS Student_Id
FROM STUDENTS;

SELECT AVG(AGE) AS Average_Age
FROM STUDENTS;

SELECT SUM(STUDENT_SCORE) AS Total_Marks
FROM STUDENTS;
