
CREATE TABLE IF NOT EXISTS STUDENT (
    ROLL_NO TEXT PRIMARY KEY,
    NAME TEXT NOT NULL,
    ADDRESS TEXT, 
    PHONE TEXT,
    AGE INTEGER
);

INSERT INTO STUDENT(ROLL_NO, NAME, ADDRESS, PHONE, AGE) VALUES
    ('1', 'RAM', 'DELHI', '098752', 18 ),
    ('2', 'RAMESH', 'GURGAON', '023564', 18),
    ('3', 'SUJIT', 'ROHTAK', '046294', 28),
    ('4', 'SURESH', 'DELHI', '033692', 18),
    ('5', 'AMAN', 'ROHTAK', '042834', 20),
    ('6', 'HARSH', 'GURGAON', '0368344', 18);

SELECT * FROM STUDENT;

SELECT * FROM STUDENT WHERE AGE = 18 AND ADDRESS = 'DELHI';

SELECT * FROM STUDENT WHERE AGE = 18 AND NAME = 'RAM';

SELECT * FROM STUDENT WHERE NAME = 'RAM' OR NAME = 'SUJIT';

SELECT * FROM STUDENT WHERE NAME = 'RAM' OR AGE = 28;

SELECT * FROM STUDENT WHERE AGE = 18 AND (NAME = 'RAM' OR NAME = 'RAMESH');


